from django.conf import settings
from django.urls import include, path

from . import views


admin_urlpatterns = [
    path("auth/login", views.admin_login),
    path("tenants", views.admin_tenants),
    path("tenants/", views.admin_tenants),
    path("tenants/stats/summary", views.admin_stats),
    path("system/stats", views.admin_system_stats),
    path("system", views.admin_system),
    path("system/migrations", views.admin_system_migrations),
    path("subscriptions", views.admin_subscriptions),
    path("subscriptions/revenue-chart", views.admin_revenue_chart),
    path("subscriptions/<int:subscription_id>", views.admin_subscriptions),
    path("subscriptions/<int:subscription_id>/payments", views.admin_subscription_payments),
    path("tenants/<str:tenant_id>/subscription", views.admin_tenant_subscription),
    path("tenants/<str:tenant_id>/subscription/remind", views.admin_subscription_remind),
    path("tenants/<str:tenant_id>/mikrotik/test", views.admin_mikrotik_test),
    path("tenants/audit/logs", views.admin_audit_logs),
    path("tenants/<str:tenant_id>", views.admin_tenants),
    path("tenants/<str:tenant_id>/<str:child>", views.admin_tenants),
    path("site", views.admin_site),
    path("site/", views.admin_site),
    path("users", views.admin_users),
    path("users/", views.admin_users),
    path("users/<str:tenant_id>/<str:customer_id>", views.admin_users),
    path("users/<str:tenant_id>/<str:customer_id>/<str:action>", views.admin_users),
]

urlpatterns = [
    path("health", views.health),
    path("health/", views.health),
    path("auth/register", views.auth_register),
    path("auth/login", views.auth_login),
    path("public/site", views.public_site),
    path("public/stats", views.public_stats),
    path("public/<str:tenant_id>", views.public_tenant),
    path("public/<str:tenant_id>/packages", views.public_packages),
    path("public/<str:tenant_id>/pay", views.public_pay),
    path("public/<str:tenant_id>/redeem", views.public_redeem),
    path("public/<str:tenant_id>/verify", views.public_verify),
    path("captive/<str:tenant_id>", views.captive_portal_page),
    path("captive/<str:tenant_id>/pay", views.captive_portal_pay),
    path("dashboard/stats", views.dashboard_stats),
    path("customers", views.customers),
    path("customers/", views.customers),
    path("customers/add", views.customer_add),
    path("customers/hotspot-portal", views.customer_hotspot_portal),
    path("customers/<str:customer_id>", views.customers),
    path("customers/<str:customer_id>/provision", views.customer_provision),
    path("customers/<str:customer_id>/renew", views.customer_renew),
    path("packages", views.packages),
    path("packages/", views.packages),
    path("packages/add", views.package_add),
    path("packages/router/profiles", views.router_profiles),
    path("router/status", views.router_status),
    path("router/ports", views.router_ports),
    path("router/reboot", views.router_reboot),
    path("router/resources", views.router_resources),
    path("router/provision-command", views.router_provision_command),
    path("router/provision/<str:token>", views.router_provision_script),
    path("router/provision/<str:token>/complete", views.router_provision_complete),
    path("router/provision/<str:token>/snapshot/<str:section>", views.router_provision_snapshot),
    path("router/agent/<str:token>/poll", views.router_agent_poll),
    path("router/agent/<str:token>/ack/<str:command_id>", views.router_agent_ack),  
    path("packages/sync-all", views.package_sync),
    path("packages/<str:package_id>", views.packages),
    path("packages/<str:package_id>/sync", views.package_sync),
    path("payments", views.payments),
    path("payments/", views.payments),
    path("payments/pay", views.payments),
    path("payments/<str:payment_id>/mark-paid", views.payment_mark_paid),
    path("reports/revenue", views.report_revenue),
    path("reports/customers", views.report_customers),
    path("reports/packages", views.report_packages),
    path("reports/expenses", views.report_expenses),
    path("profile", views.profile),
    path("settings/business", views.settings_business),
    path("settings/logo", views.settings_logo),
    path("settings/test-sms", views.settings_test_sms),
    path("settings/delete-customers", views.settings_delete_customers),
    path("settings/mikrotik", views.settings_mikrotik),
    path("settings/mikrotik/test", views.settings_mikrotik_test),
    path("settings/notifications", views.settings_notifications),
    path("tickets", views.tickets),
    path("tickets/add", views.tickets),
    path("tickets/<str:ticket_id>", views.tickets),
    path("paystack/webhook", views.paystack_webhook),
    path("paystack/callback", views.paystack_callback),
    path(f"{settings.ADMIN_API_PATH}/", include(admin_urlpatterns)),
]
